### ISSUE TITLE
노준영 Milestone

### ISSUE THREAD

**Issue by ghgt1** [pre-onboarding-Team-4/pre-onboarding-11th-1-4#10]
## 요구사항

- 프로젝트 초기세팅 및 Git Branch관리

## 작업리스트

- [x] 프로젝트에 필요한 라이브러리 설치
- [x] Airbnb-Eslint, Prettier Config 설정 
- [x] Husky lint-staged를 활용한 Git hook action
- [x] GlobalStyle파일 작성 및 적용(Reset css, 변수 선언)
- [x] Develop 브랜치로 Merge

## 참고사항

- 각자 PR 마감은 금요일 12시(정오)입니다!
- 작업중 궁금한 사항은 언제든지 물어봐주세요 👍
